### ISSUE TITLE
astro-eslint-parser fails to parse react-toastify module: parser.parse is not a function

### ISSUE THREAD

**Issue by corneliusroemer** [ota-meshi/eslint-plugin-astro#452]
### Before You File a Bug Report Please Confirm You Have Done The Following...

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have updated to the latest version of the packages.

### What version of ESLint are you using?

8.57.0

### What version of `eslint-plugin-astro` are you using?

1.3.1

### What did you do?

1. Clone the repository: [loculus-project/loculus](https://github.com/loculus-project/loculus).
2. Checkout the commit: [654535a](https://github.com/loculus-project/loculus/pull/3231/commits/654535a3417f83997594887cd4bd2ee605c8901e).
3. Run `cd website && npm ci`.
4. Run the linting command: `npm run check-format`.

### What did you expect to happen?

No errors

### What actually happened?

```
Error while parsing /Users/corneliusromer/code/loculus/website/node_modules/react-toastify/dist/react-toastify.esm.mjs
Line 4, column 0: Unknown token at 15459, expected: "}", actual: ""
`parseForESLint` from parser `/Users/corneliusromer/code/loculus/website/node_modules/astro-eslint-parser/lib/index.js` is invalid and will just be ignored

Error while parsing /Users/corneliusromer/code/loculus/website/node_modules/react-toastify/dist/react-toastify.esm.mjs
Line 4, column 0: Unknown token at 15459, expected: "}", actual: ""
`parseForESLint` from parser `/Users/corneliusromer/code/loculus/website/node_modules/astro-eslint-parser/lib/index.js` is invalid and will just be ignored

/Users/corneliusromer/code/loculus/website/src/layouts/BaseLayout.astro
  3:32  warning  Parse errors in imported module 'react-toastify': parser.parse is not a function (undefined:undefined)  import/no-deprecated
```

### Link to Minimal Reproducible Example

https://github.com/loculus-project/loculus/pull/3231/commits/654535a3417f83997594887cd4bd2ee605c8901e

### Additional comments

I do'nt quite know why this error surfaced only now. It happens when I upgrade `eslint-plugin-import` from 2.29.1 to 2.31.0 - many components seem to come together here creating a strange end result.

Here's the dependabot PR that first surfaced this: https://github.com/loculus-project/loculus/pull/3231

Let me know if I should file an issue elsewhere, for now there is at least some strange parsing going on here?

**Comment by corneliusroemer** [comment]
It turns out others have faced this issue as well:
- https://github.com/GenSpectrum/dashboards/blob/4b627465912c18846b8344fa8b69743e0c88ccbd/website/src/components/auth/UserDropdown.astro#L2
- https://github.com/GenSpectrum/dashboards/blob/4b627465912c18846b8344fa8b69743e0c88ccbd/website/src/pages/500.astro#L2
- https://github.com/GenSpectrum/dashboards/blob/4b627465912c18846b8344fa8b69743e0c88ccbd/website/src/layouts/base/BaseLayout.astro#L2
- https://github.com/SaekiTominaga/w0s.jp/blob/616ce8007c0e11d46b2b8d3695ac68d82c899d56/astro/eslint.config.js#L35-L39

**Comment by gambolputty** [comment]
I had a similar error and the solution was to tell ESLint which parser to use for *.mjs files because it was missing in my config:

```js
"import/parsers": {
  "@typescript-eslint/parser": [".ts", ".tsx", ".mjs"],
  "astro-eslint-parser": [".astro"],
},
```
